name: "ci: use pinned requirements + pytest"

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements-ci.txt

      - name: Install deps (pinned for CI)
        run: |
          python -V
          pip install -U pip
          pip install -r requirements-ci.txt
          python - <<'PY'
          import importlib
          for m in ["pandas","duckdb","altair","nfl_data_py","pyarrow","pytest"]:
              try:
                  mod = importlib.import_module(m)
                  print(m, getattr(mod, "__version__", "unknown"))
              except Exception as e:
                  print("FAILED", m, e)
          PY

      - name: Build data (bronze → silver → gold)
        run: |
          mkdir -p data/bronze data/silver data/gold db
          python scripts/bronze_ingest.py --years "2024" --player "Lamar Jackson"
          python scripts/silver_transform.py
          python scripts/gold_build.py

      - name: Show gold sample (debug)
        run: |
          python - <<'PY'
          import pandas as pd
          df = pd.read_csv("data/gold/fact_lamar_weekly.csv")
          print("rows:", len(df), "cols:", list(df.columns))
          print(df.head().to_string(index=False))
          PY

      - name: Run pytest
        run: python -m pytest -q
