name: "ci: use pinned requirements + pytest"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements-ci.txt

      - name: Install deps (pinned for CI)
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements-ci.txt

      # 🔽 build the small dataset needed by tests
      - name: Build bronze→silver→gold (minimal)
        run: |
          mkdir -p data/bronze data/silver data/gold db
          python scripts/bronze_ingest.py --years "2024" --player "Lamar Jackson"
          python scripts/silver_transform.py
          python scripts/gold_build.py

      - name: Run tests
        run: python -m pytest -q
