name: ci

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/report.yml'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare DB (bronze→silver→gold)
        run: |
          mkdir -p data/bronze data/silver data/gold db
          python scripts/bronze_ingest.py --years "2024" --player "Lamar Jackson"
          python scripts/silver_transform.py
          python scripts/gold_build.py

      - name: Run tests
        run: pytest -q
