name: "ci: run tests"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            requirements-ci.txt

      - name: Install dependencies (pinned)
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements-ci.txt
          python - <<'PY'
          import importlib
          for m in ["pandas","duckdb","altair","nfl_data_py","pyarrow","pytest"]:
              mod = importlib.import_module(m)
              print(f"{m}: {getattr(mod,'__version__','unknown')}")
          PY

      - name: Build data for tests (bronze → silver → gold)
        run: |
          mkdir -p data/bronze data/silver data/gold db
          python scripts/bronze_ingest.py --years "2024" --player "Lamar Jackson"
          python scripts/silver_transform.py
          python scripts/gold_build.py

      - name: Show gold sample (debug)
        run: |
          ls -la data/gold || true
          python - <<'PY'
          import os, pandas as pd
          p = "data/gold/fact_lamar_weekly.csv"
          print("gold exists:", os.path.exists(p))
          if os.path.exists(p):
              df = pd.read_csv(p)
              print("rows:", len(df), "cols:", list(df.columns))
              print(df.head().to_string(index=False))
          PY

      - name: Run pytest
        run: |
          python -m pytest -q
