name: "ci: use pinned requirements + pytest"

on:
  push:
    paths-ignore:
      - 'docs/**'     # ignore report publishes
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements-ci.txt

      - name: Install deps (pinned)
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements-ci.txt
          python - <<'PY'
          import importlib
          for m in ["pandas","duckdb","altair","nfl_data_py","pyarrow"]:
              mod = importlib.import_module(m)
              print(m, getattr(mod, "__version__", "unknown"))
          PY

      - name: Run tests
        run: pytest -q
