name: Build & Publish Lamar Report

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 * * 2"   # Tue 12:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline (Bronze → Silver)
        run: |
          mkdir -p data/bronze data/silver data/gold db
          python scripts/bronze_ingest.py --years "2024" --player "Lamar Jackson"
          python scripts/silver_transform.py

      - name: Validate data quality (Great Expectations)
        run: |
          python scripts/validate_data.py   # job fails if this raises

      - name: Build Gold + Static report
        run: |
          python scripts/gold_build.py
          python scripts/build_static_report.py
          touch docs/.nojekyll

      - name: Commit & push report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/index.html docs/.nojekyll
          if ! git diff --cached --quiet; then
            git commit -m "chore(report): refresh static HTML [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
