name: Build & Publish Lamar Report

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements-ci.txt

      - name: Install deps (pinned)
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements-ci.txt
          python - <<'PY'
          import importlib, sys
          for m in ["pandas","duckdb","altair","nfl_data_py","pyarrow"]:
              mod = importlib.import_module(m)
              print(f"{m} {getattr(mod,'__version__', 'unknown')}")
          PY

      - name: Build bronze→silver→gold
        run: |
          mkdir -p data/bronze data/silver data/gold db
          python scripts/bronze_ingest.py --years "2024" --player "Lamar Jackson"
          python scripts/silver_transform.py
          python scripts/gold_build.py

      - name: Build static report
        run: python scripts/build_static_report.py

      - name: Commit & push /docs
        run: |
          touch docs/.nojekyll
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/index.html docs/.nojekyll data/gold/fact_lamar_weekly.csv || true
          git commit -m "report: refresh HTML" || echo "nothing to commit"
          git push
